parameters:
  
  app:
    
    default_locale:  en
    admin_locales:   [de, en]
    
    timezone: 'Europe/Zurich' #default Timezone, users can set their own
    date_format: 'yyyy-MM-dd' #default DateFormat, users can set their own
    time_format: 'HH:mm:ss'   #default TimeFormat, users can set their own

    easyadmin:
      registration: true #allow new users to register
      passwort_reset: true #allow password reset

    mailer:
      from_email: 'team@root.dev'
      from_name: 'AcmeBotName'
      detailed_mail_log: true #log full send history with mail body to entity Email